# Generated by Django 5.1.3 on 2024-12-02 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('onlinebankingapp', '0002_alter_account_account_number_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Complaints',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('custmoer_name', models.CharField(max_length=50, unique=True)),
                ('email', models.EmailField(max_length=254)),
                ('complaint_text', models.TextField()),
            ],
        ),
    ]
