# Generated by Django 5.1.3 on 2024-12-03 13:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('onlinebankingapp', '0003_complaints'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='show_account',
            name='user',
        ),
        migrations.AddField(
            model_name='show_account',
            name='account',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='onlinebankingapp.account'),
            preserve_default=False,
        ),
    ]
