# Generated by Django 5.1.3 on 2024-12-03 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('onlinebankingapp', '0007_remove_account_balance'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='account',
            name='user',
        ),
        migrations.AddField(
            model_name='account',
            name='username',
            field=models.CharField(max_length=50, null=True, unique=True),
        ),
    ]
