# Generated by Django 5.1.3 on 2024-12-03 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('onlinebankingapp', '0009_remove_account_username_account_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='show_account',
            name='account',
        ),
        migrations.AddField(
            model_name='show_account',
            name='account',
            field=models.ManyToManyField(to='onlinebankingapp.account'),
        ),
    ]
