# Generated by Django 5.1.3 on 2024-12-03 17:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('onlinebankingapp', '0013_account_balance'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='account',
            name='balance',
        ),
    ]
