# Generated by Django 5.1.3 on 2024-12-03 18:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('onlinebankingapp', '0015_account_balance'),
    ]

    operations = [
    ]
