# Generated by Django 5.1.3 on 2024-12-03 18:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('onlinebankingapp', '0016_auto_20241203_2334'),
    ]

    operations = [
    ]
