# Generated by Django 5.1.3 on 2024-12-04 09:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('onlinebankingapp', '0017_auto_20241203_2342'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Show_Account',
        ),
    ]
