# Generated by Django 5.1.3 on 2024-12-04 10:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('onlinebankingapp', '0019_show_account'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='account',
            name='user',
        ),
        migrations.RemoveField(
            model_name='show_account',
            name='account',
        ),
        migrations.RemoveField(
            model_name='show_account',
            name='user',
        ),
        migrations.DeleteModel(
            name='Transaction',
        ),
        migrations.DeleteModel(
            name='Account',
        ),
        migrations.DeleteModel(
            name='Show_Account',
        ),
    ]
