# Generated by Django 5.1.3 on 2024-12-04 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('onlinebankingapp', '0021_account_transaction'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='account_number',
            field=models.CharField(default='9175146120', max_length=10, unique=True),
        ),
    ]
