# Generated by Django 5.1.3 on 2024-12-04 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('onlinebankingapp', '0022_alter_account_account_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='address',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='account',
            name='account_number',
            field=models.CharField(default='3990480143', max_length=10, unique=True),
        ),
    ]
